// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
// Small builders for schedule tests, so each test shows only what matters to it.
// Test-only: not exported from index.ts.
import type {
  ChunkHistory,
  DateOnly,
  PlannedSession,
  ScheduleChunk,
  ScheduleExam,
  ScheduleInput,
  ScheduleOutput,
  ScheduleTopic,
} from '../types/index.ts';
import { SESSIONS_PER_DAY } from '../types/index.ts';
import { toWorkingChunks, type WorkingChunk } from './chunk-state.ts';
import { addDays } from './dates.ts';

/** A fixed Monday, so tests never depend on the real date. */
export const TODAY: DateOnly = '2026-11-02';

/** The day `n` days after TODAY. */
export const day = (n: number): DateOnly => addDays(TODAY, n);

/** A chunk with `questions` questions named "<id>-q1", "<id>-q2", ..., and no history unless given. */
export function chunk(
  id: string,
  topicId: string | null,
  options: Partial<ChunkHistory> & { questions?: number } = {},
): ScheduleChunk {
  const { questions = 3, ...history } = options;
  return {
    id,
    topicId,
    questionIds: Array.from({ length: questions }, (_, i) => `${id}-q${i + 1}`),
    history: { correctSessions: 0, lastSeen: null, lastCorrect: null, ...history },
  };
}

export function topic(id: string, difficulty: ScheduleTopic['difficulty'] = null): ScheduleTopic {
  return { id, difficulty };
}

/**
 * An exam with `topics` topics ("<id>-t1", ...) and `perTopic` fresh chunks
 * each ("<id>-t1-c1", ...), every chunk with 3 questions.
 */
export function exam(id: string, examDate: DateOnly, topics = 3, perTopic = 2): ScheduleExam {
  const topicList = Array.from({ length: topics }, (_, i) => topic(`${id}-t${i + 1}`));
  const chunks = topicList.flatMap((t) =>
    Array.from({ length: perTopic }, (_, j) => chunk(`${t.id}-c${j + 1}`, t.id)),
  );
  return { id, examDate, topics: topicList, chunks };
}

/** A full input with pace normal, no busy days and nothing kept, unless overridden. */
export function input(overrides: Partial<ScheduleInput> & Pick<ScheduleInput, 'exams'>): ScheduleInput {
  return { today: TODAY, pace: 'normal', busyDays: [], keep: [], ...overrides };
}

/** Working chunks of an exam, for testing pick.ts and chunk-state.ts directly. */
export function working(e: ScheduleExam): WorkingChunk[] {
  return toWorkingChunks(e);
}

/** The days that have a session for one exam, in order. */
export function daysOf(out: ScheduleOutput, examId: string): DateOnly[] {
  return out.sessions.filter((s) => s.examId === examId).map((s) => s.scheduledFor);
}

/** Every chunk id a session touches, read back from the "<chunk>-qN" question ids. */
export function chunksIn(session: PlannedSession): string[] {
  return [...new Set(session.questionIds.map((q) => q.replace(/-q\d+$/, '')))];
}

/**
 * Rules that must hold for every output. Throws with a readable message on the
 * first one broken, so a scenario test can call it after its own checks.
 */
export function assertInvariants(inp: ScheduleInput, out: ScheduleOutput): void {
  const cap = SESSIONS_PER_DAY[inp.pace];
  const examDate = new Map(inp.exams.map((e) => [e.id, e.examDate]));
  const perDay = new Map<DateOnly, number>();
  const examDay = new Set<string>();
  for (const k of inp.keep) {
    if (k.scheduledFor < inp.today) continue;
    perDay.set(k.scheduledFor, (perDay.get(k.scheduledFor) ?? 0) + 1);
    examDay.add(`${k.examId}|${k.scheduledFor}`);
  }
  let previous = '';
  for (const s of out.sessions) {
    const where = `${s.examId} on ${s.scheduledFor}`;
    if (s.scheduledFor < previous) throw new Error(`sessions not sorted by day at ${where}`);
    previous = s.scheduledFor;
    if (s.scheduledFor < inp.today) throw new Error(`session before today: ${where}`);
    if (s.scheduledFor >= examDate.get(s.examId)!) throw new Error(`session on or after the exam: ${where}`);
    if (inp.busyDays.includes(s.scheduledFor)) throw new Error(`session on a busy day: ${where}`);
    const key = `${s.examId}|${s.scheduledFor}`;
    if (examDay.has(key)) throw new Error(`two sessions for one exam on one day: ${where}`);
    examDay.add(key);
    const load = (perDay.get(s.scheduledFor) ?? 0) + 1;
    if (load > cap) throw new Error(`more than ${cap} sessions on ${s.scheduledFor}`);
    perDay.set(s.scheduledFor, load);
    if (s.questionIds.length < 1 || s.questionIds.length > 7) throw new Error(`${s.questionIds.length} questions: ${where}`);
    if (!s.isFinalPass && s.topicIds.length > 3) throw new Error(`more than 3 topics: ${where}`);
    if (new Set(s.questionIds).size !== s.questionIds.length) throw new Error(`a question twice in one session: ${where}`);
  }
}
