// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
import { SESSIONS_PER_DAY, type DateOnly, type Id, type ScheduleInput } from '../types/index.ts';
import { addDays, daysBetween } from './dates.ts';
import { gapDays } from './gap.ts';

/** Questions a normal session is counted as holding when judging whether the rhythm is enough (rule 7). */
export const SESSION_TARGET = 6;

/** Which days are taken: busy days, kept sessions and sessions placed so far. */
export interface Calendar {
  /** Most sessions on one day across all exams (rule 6, from the pace). */
  cap: number;
  busy: Set<DateOnly>;
  /** Sessions on each day, all exams, kept ones included. */
  load: Map<DateOnly, number>;
  /** "examId|day" for every exam that already has a session that day. */
  examDays: Set<string>;
}

export function makeCalendar(input: ScheduleInput): Calendar {
  const calendar: Calendar = {
    cap: SESSIONS_PER_DAY[input.pace],
    busy: new Set(input.busyDays),
    load: new Map(),
    examDays: new Set(),
  };
  for (const k of input.keep) {
    if (k.scheduledFor >= input.today) take(calendar, k.examId, k.scheduledFor);
  }
  return calendar;
}

/** Rule 6: not busy, no session for this exam yet that day, and under the daily cap. */
export function canPlace(calendar: Calendar, examId: Id, day: DateOnly): boolean {
  return (
    !calendar.busy.has(day) &&
    !calendar.examDays.has(`${examId}|${day}`) &&
    (calendar.load.get(day) ?? 0) < calendar.cap
  );
}

/** Books one session for the exam on that day. */
export function take(calendar: Calendar, examId: Id, day: DateOnly): void {
  calendar.load.set(day, (calendar.load.get(day) ?? 0) + 1);
  calendar.examDays.add(`${examId}|${day}`);
}

/**
 * Rule 8: book the final pass on the latest free day before the exam (the day
 * before, unless that day is busy, kept or full). Called closest exam first,
 * before any normal session, so final passes win their day. Null when no day
 * from today to the day before the exam is free.
 */
export function reserveFinalPass(
  calendar: Calendar,
  examId: Id,
  today: DateOnly,
  examDate: DateOnly,
): DateOnly | null {
  for (let day = addDays(examDate, -1); day >= today; day = addDays(day, -1)) {
    if (canPlace(calendar, examId, day)) {
      take(calendar, examId, day);
      return day;
    }
  }
  return null;
}

/** Rule 7: the next on-rhythm day after a session on `day`. */
export function nextRhythmDay(day: DateOnly, examDate: DateOnly): DateOnly {
  return addDays(day, gapDays(daysBetween(day, examDate)));
}

/** On-rhythm days from `from` up to, not including, `end`. Busy days are not subtracted: an estimate. */
export function rhythmDaysLeft(from: DateOnly, end: DateOnly, examDate: DateOnly): number {
  let n = 0;
  for (let day = from; day < end; day = nextRhythmDay(day, examDate)) n++;
  return n;
}

/** Rule 7: the recalls still needed do not fit in the on-rhythm sessions left. */
export function isBehind(recallsNeeded: number, rhythmDays: number): boolean {
  return recallsNeeded > rhythmDays * SESSION_TARGET;
}
