// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
import {
  SCHEDULE_WARNING_CODES,
  type Id,
  type ScheduleWarning,
  type ScheduleWarningCode,
} from '../types/index.ts';

/** Collects warnings while the plan is built: each one once, then sorted so the output is deterministic. */
export class WarningList {
  private readonly byKey = new Map<string, ScheduleWarning>();

  add(code: ScheduleWarningCode, examId: Id | null, chunkId?: Id): void {
    const key = `${code}|${examId ?? ''}|${chunkId ?? ''}`;
    if (this.byKey.has(key)) return;
    // chunkId is left out entirely when absent, so warnings compare cleanly with toEqual.
    this.byKey.set(key, chunkId === undefined ? { code, examId } : { code, examId, chunkId });
  }

  /** By code in SCHEDULE_WARNING_CODES order, then exam id, then chunk id. */
  list(): ScheduleWarning[] {
    const rank = (w: ScheduleWarning) => SCHEDULE_WARNING_CODES.indexOf(w.code);
    const text = (v: string | null | undefined) => v ?? '';
    const byText = (x: string, y: string) => (x < y ? -1 : x > y ? 1 : 0);
    return [...this.byKey.values()].sort(
      (a, b) =>
        rank(a) - rank(b) ||
        byText(text(a.examId), text(b.examId)) ||
        byText(text(a.chunkId), text(b.chunkId)),
    );
  }
}
