// Copies packages/shared/src into supabase/functions/_shared/schedule so the
// Deno Edge Functions can import the schedule engine. Deno needs explicit
// ".ts" endings on relative imports; the app's bundler does not, so the copy
// rewrites them. Test files are not copied.
//
//   npm run sync-engine                       refresh the copy
//   node scripts/sync-engine.mjs --check      exit 1 if the copy is stale
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'packages', 'shared', 'src');
const OUT = join(root, 'supabase', 'functions', '_shared', 'schedule');
const HEADER = '// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.\n';

function listTs(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return listTs(path);
    return entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts') ? [path] : [];
  });
}

function rewriteImports(code, fileDir) {
  return code.replace(/(from\s+['"])(\.{1,2}\/[^'"]+)(['"])/g, (match, open, spec, close) => {
    if (spec.endsWith('.ts')) return match;
    const target = resolve(fileDir, spec);
    if (existsSync(`${target}.ts`)) return `${open}${spec}.ts${close}`;
    if (existsSync(join(target, 'index.ts'))) return `${open}${spec}/index.ts${close}`;
    throw new Error(`sync-engine: cannot resolve "${spec}" in ${fileDir}`);
  });
}

function normalise(text) {
  // Git on Windows may check files out with CRLF; compare and write with LF.
  return text.replace(/\r\n/g, '\n');
}

function expectedFiles() {
  const files = new Map();
  for (const file of listTs(SRC)) {
    const rel = relative(SRC, file).split('\\').join('/');
    files.set(rel, HEADER + rewriteImports(normalise(readFileSync(file, 'utf8')), dirname(file)));
  }
  return files;
}

function actualFiles() {
  if (!existsSync(OUT)) return new Map();
  return new Map(
    listTs(OUT).map((file) => [relative(OUT, file).split('\\').join('/'), normalise(readFileSync(file, 'utf8'))]),
  );
}

const want = expectedFiles();

if (process.argv.includes('--check')) {
  const have = actualFiles();
  const names = [...new Set([...want.keys(), ...have.keys()])].sort();
  const stale = names.filter((name) => want.get(name) !== have.get(name));
  if (stale.length > 0) {
    console.error(`Engine copy is out of date: ${stale.join(', ')}\nRun: npm run sync-engine`);
    process.exit(1);
  }
  console.log('Engine copy is in sync.');
} else {
  rmSync(OUT, { recursive: true, force: true });
  for (const [rel, text] of want) {
    const path = join(OUT, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
  }
  console.log(`Copied ${want.size} files to supabase/functions/_shared/schedule`);
}
