// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
import type { Id, Timestamp } from './common.ts';

/**
 * The secret behind a student's calendar link. The link looks like
 * .../calendar-feed?token=... and returns the student's sessions and exam
 * dates as an .ics file. Anyone with the token can read that feed, so the
 * student can delete the row to make a new one.
 *
 * Cramrade only sends to the calendar. It never reads it.
 *
 * Table: calendar_feeds. One row per student, visible to that student only.
 */
export interface CalendarFeed {
  userId: Id;
  /** Random secret made by the database. */
  token: string;
  createdAt: Timestamp;
}
