// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
// Small building blocks used by every data shape.
//
// Column names in the database are snake_case (exam_date). Fields here are
// camelCase (examDate). The app maps one to the other when it reads or writes.

/** A row id. Every table uses a random UUID made by the database. */
export type Id = string;

/** A point in time as an ISO 8601 string, for example "2026-10-05T14:30:00Z". The database stores it as timestamptz. */
export type Timestamp = string;

/** A calendar day with no time, as "YYYY-MM-DD". The database stores it as date. */
export type DateOnly = string;
