// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
// The data shapes agreed in task T1. One file per area, all re-exported here.
// Each shape matches one database table in supabase/migrations.
export type { Id, Timestamp, DateOnly } from './common.ts';
export type { Profile } from './profile.ts';
export type { Group, GroupMember, GroupRole } from './group.ts';
export type { Exam, ExamKind, ExamSource, Topic } from './exam.ts';
export type { Note, NoteSource, NoteStatus, Chunk } from './note.ts';
export type { Question, QuestionKind } from './question.ts';
export type { StudySession, StudySessionStatus, SessionQuestion, Attempt } from './session.ts';
export type {
  QuizRoom,
  QuizRoomStatus,
  QuizMode,
  QuizRoomQuestion,
  QuizPlayer,
  QuizAnswer,
} from './quiz.ts';
export type { CalendarFeed } from './calendar.ts';
export type { StudySettings, BusyDay } from './settings.ts';
export type {
  Pace,
  ScheduleWarning,
  ScheduleWarningCode,
  ChunkHistory,
  ScheduleChunk,
  ScheduleTopic,
  ScheduleExam,
  ScheduleInput,
  PlannedSession,
  ScheduleOutput,
} from './schedule.ts';

// The allowed-value lists behind the union types, for pickers and checks.
// Agreed in T1 (2026-10-10): screens read these instead of typing the values again.
export { EXAM_KINDS, EXAM_SOURCES } from './exam.ts';
export { GROUP_ROLES } from './group.ts';
export { NOTE_SOURCES, NOTE_STATUSES } from './note.ts';
export { QUESTION_KINDS } from './question.ts';
export { QUIZ_ROOM_STATUSES, QUIZ_MODES } from './quiz.ts';
export { STUDY_SESSION_STATUSES } from './session.ts';
export { PACES, SESSIONS_PER_DAY, SCHEDULE_WARNING_CODES } from './schedule.ts';
