// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
import type { Id, Timestamp } from './common.ts';

/** The form of the question on the screen. */
export const QUESTION_KINDS = ['multiple_choice', 'short_answer', 'flashcard'] as const;
export type QuestionKind = (typeof QUESTION_KINDS)[number];

/**
 * One question made from the student's notes. Written only by the server
 * (the question maker), never by the app.
 *
 * Every question traces to one chunk: sourceQuote is text copied from that
 * chunk, and the database checks the quote really appears in the chunk's text
 * and sets verified from that. The app should only show verified questions.
 *
 * Table: questions. Same visibility as its note. The note's owner can delete
 * a question; nobody can edit one.
 */
export interface Question {
  id: Id;
  noteId: Id;
  /** The chunk the question was made from. Must belong to noteId. */
  chunkId: Id;
  /** The exam this question helps with, if known. */
  examId: Id | null;
  /** The topic inside that exam, if known. */
  topicId: Id | null;
  kind: QuestionKind;
  /** The question text. For a flashcard, the front of the card. */
  prompt: string;
  /** The options for a multiple-choice question. Null for the other kinds. */
  choices: string[] | null;
  /** The correct answer. For multiple choice it is one of the choices, word for word. For a flashcard, the back of the card. */
  answer: string;
  /** Text copied word for word from the chunk, shown as "this is where it is in your notes". */
  sourceQuote: string;
  /** True when the database confirmed sourceQuote appears in the chunk's text. */
  verified: boolean;
  createdAt: Timestamp;
}
