// GENERATED by scripts/sync-engine.mjs from packages/shared/src. Do not edit here.
import type { DateOnly, Id, Timestamp } from './common.ts';
// Pace (light, normal, heavy) and PACES belong to the schedule engine.
import type { Pace } from './schedule.ts';

/**
 * The student's study plan settings. One row per student, created by the app
 * the first time the settings screen saves. When the row is missing, the
 * server uses the defaults shown below.
 *
 * Table: study_settings. Visible to and editable by the student only.
 */
export interface StudySettings {
  userId: Id;
  /** The most sessions per day across all exams: light 1, normal 2, heavy 3. Default 'normal'. */
  pace: Pace;
  /** Weekdays with no sessions: 0 = Sunday, 1 = Monday ... 6 = Saturday. Default none. */
  daysOff: number[];
  /** Usual time of day for a session, as the database returns it: "18:00:00". Default 18:00. */
  sessionTime: string;
  /** IANA time zone name, for example "Europe/Berlin". Default "UTC". */
  timeZone: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * Dates the student cannot study, fromDate to toDate inclusive (one day:
 * both the same). The schedule engine places no session on these days.
 *
 * Table: busy_days. Visible to and editable by the student only.
 */
export interface BusyDay {
  id: Id;
  userId: Id;
  fromDate: DateOnly;
  toDate: DateOnly;
  /** Optional, shown back to the student, for example "football trip". Up to 120 characters. */
  reason: string | null;
  createdAt: Timestamp;
}
